# Generated by Django 3.2.7 on 2021-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211001_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='thumbnails/'),
        ),
    ]
