# Generated by Django 3.2.7 on 2021-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_music_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
